keys:
  - &stinjul_zentoo age17gj5x2w8c46lepd2j9vj592atxcfpg2dl59vwza4qfdje8yw6vsqh926gr
  - &stinjul_wsl age1hux2w96t957ym0m9q3y2hkfljs6mnsmp2sc86lvztf7emtdr29yq9hfae6
  - &stinjul_nixtop age1syqdhere86l4d87jujju05e0sqqh6nqe5spjtthtnd2z7wvj7vjqv99hfm
  - &mgmt_pi age1h996uvpeu3cl92sg20ygenurrf5z75yacym8qr2fa5eyv2cp6pqqkl9xnk

keychain:
  - &stinjul_wsl_chain >-
    age17gj5x2w8c46lepd2j9vj592atxcfpg2dl59vwza4qfdje8yw6vsqh926gr,
    age1hux2w96t957ym0m9q3y2hkfljs6mnsmp2sc86lvztf7emtdr29yq9hfae6


creation_rules:
  - path_regex: home-manager/stinjul/global/secrets.yaml
    age: *stinjul_zentoo
  - path_regex: home-manager/stinjul/wsl/secrets.yaml
    key_groups:
      - age:
        - *stinjul_zentoo
        - *stinjul_wsl
  - path_regex: hosts/common/secrets.yaml
    key_groups:
      - age:
        - *stinjul_zentoo
        - *stinjul_nixtop
        - *mgmt_pi
  - path_regex: hosts/homelab/secrets.yaml
    key_groups:
      - age:
        - *stinjul_zentoo
        - *stinjul_nixtop
        - *mgmt_pi
