env:
  es2022: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  sourceType: "module"
  project: "./tsconfig.json"
  warnOnUnsupportedTypeScriptVersion: false
root: true
ignorePatterns:
  - types/
plugins:
  - "@typescript-eslint"
globals:
  Widget: readonly
  Utils: readonly
  App: readonly
  Variable: readonly
  Service: readonly
  console: readonly
